In [ ]:
import pandas as pd

raw_data = pd.read_csv("scraped_data.csv")

# randomly selecting 1,000 jobs to be the new dataset
raw_1000 = raw_data.sample(n=1000, random_state=1)
# dropping Unnamed: 0 column
raw_1000 = raw_1000.drop(columns=["Unnamed: 0"])
# reset index
raw_1000 = raw_1000.reset_index(drop=True)
raw_1000.head()

,job_title,job_location,job_salary,job_summary
0,Manager Data Analytics,"Worcester, MA 01605",NaN,\nThe Manager Data Analytics will establish an...
1,Machine Learning Architect (Senior Consultant)...,"Philadelphia, PA 19103",NaN,\n Are you looking for an organization with st...
2,DATABASE ARCHITECT,"Dallas, TX 75251",NaN,"\n\nStrideCare, a healthcare multi-specialty p..."
3,"Senior Backend Engineer, AI","Denver, CO 80123","$150,000 - $190,000 a year",Who is Recruiting from Scratch:\n Recruiting f...
4,Senior Data Scientist,"Washington, DC",NaN,\n Overview: \n \n LMI is seeking a skilled ...

In [17]:
# removing '\n' characters from job descriptions because AI generated jobs do not have it
raw_1000['job_summary'] = raw_1000['job_summary'].str.replace('\n', ' ')
# Adding target column with 0 for not AI generated
raw_1000['is_AI'] = 0
raw_1000.head()

,job_title,job_location,job_salary,job_summary,is_AI
0,Manager Data Analytics,"Worcester, MA 01605",NaN,The Manager Data Analytics will establish and...,0
1,Machine Learning Architect (Senior Consultant)...,"Philadelphia, PA 19103",NaN,Are you looking for an organization with sta...,0
2,DATABASE ARCHITECT,"Dallas, TX 75251",NaN,"StrideCare, a healthcare multi-specialty phy...",0
3,"Senior Backend Engineer, AI","Denver, CO 80123","$150,000 - $190,000 a year",Who is Recruiting from Scratch: Recruiting fr...,0
4,Senior Data Scientist,"Washington, DC",NaN,Overview: LMI is seeking a skilled Dat...,0

In [10]:
# saving data
raw_1000.to_csv("raw_1000.csv", index=False)

In [18]:
# AI jobs
raw_AI = pd.read_csv("ai_job_postings_1000-2.csv")
raw_AI['is_AI'] = 1
raw_AI.head()

,job_title,job_location,job_salary,job_summary,is_AI
0,NLP Engineer,"San Francisco, CA 94105","$90,000 - $115,000 a year",StratEdge Consulting is a boutique management ...,1
1,Senior Data Engineer,"Chicago, IL 60601","$70,000 - $90,000 a year",HorizonMind Analytics is a high-growth analyti...,1
2,Research Engineer – NLP,"Salt Lake City, UT 84101","$140,000 - $175,000 a year",Meridian Data Solutions is a cutting-edge data...,1
3,Business Intelligence Analyst,"Richmond, VA 23219",NaN,HorizonMind Analytics is a high-growth analyti...,1
4,AI Solutions Architect,"New York, NY","$80,000 - $100,000 a year",Synapse Analytics is a forward-thinking analyt...,1

In [22]:
# combining datasets
combined = pd.concat([raw_1000, raw_AI], ignore_index=True)
# shuffling raw order to mix up the postings
combined = combined.sample(frac=1, random_state=1).reset_index(drop=True)
combined.head()
# saving combined dataset
combined.to_csv("combined.csv", index=False)

In [23]:
# number of entries in combined:
len(combined)

2000

In [ ]:
# NLTK to remove stopwords?