In [8]:
import pandas as pd

raw_data = pd.read_csv("scraped_data.csv")

# randomly selecting 1,500 jobs to be the new dataset
raw_1500 = raw_data.sample(n=1500, random_state=1)
# dropping Unnamed: 0 column
raw_1500 = raw_1500.drop(columns=["Unnamed: 0"])
# reset index
raw_1500 = raw_1500.reset_index(drop=True)
raw_1500.head()

,job_title,job_location,job_salary,job_summary
0,Manager Data Analytics,"Worcester, MA 01605",NaN,\nThe Manager Data Analytics will establish an...
1,Machine Learning Architect (Senior Consultant)...,"Philadelphia, PA 19103",NaN,\n Are you looking for an organization with st...
2,DATABASE ARCHITECT,"Dallas, TX 75251",NaN,"\n\nStrideCare, a healthcare multi-specialty p..."
3,"Senior Backend Engineer, AI","Denver, CO 80123","$150,000 - $190,000 a year",Who is Recruiting from Scratch:\n Recruiting f...
4,Senior Data Scientist,"Washington, DC",NaN,\n Overview: \n \n LMI is seeking a skilled ...

In [11]:
# removing '\n' characters from job descriptions because AI generated jobs do not have it
raw_1500['job_summary'] = raw_1500['job_summary'].str.replace('\n', ' ')
# Adding target column with 0 for not AI generated
raw_1500['is_AI'] = 0
raw_1500['source'] = 'human'
raw_1500.head()

,job_title,job_location,job_salary,job_summary,is_AI,source
0,Manager Data Analytics,"Worcester, MA 01605",NaN,The Manager Data Analytics will establish and...,0,human
1,Machine Learning Architect (Senior Consultant)...,"Philadelphia, PA 19103",NaN,Are you looking for an organization with sta...,0,human
2,DATABASE ARCHITECT,"Dallas, TX 75251",NaN,"StrideCare, a healthcare multi-specialty phy...",0,human
3,"Senior Backend Engineer, AI","Denver, CO 80123","$150,000 - $190,000 a year",Who is Recruiting from Scratch: Recruiting fr...,0,human
4,Senior Data Scientist,"Washington, DC",NaN,Overview: LMI is seeking a skilled Dat...,0,human

In [12]:
# saving data
raw_1500.to_csv("raw_1500.csv", index=False)

In [21]:
# AI jobs
raw_claude = pd.read_csv("claude_data.csv")
# choose 300 random samples from the dataset
raw_claude = raw_claude.sample(n=300, random_state=1)
raw_claude['is_AI'] = 1
raw_claude['source'] = 'claude ai'
raw_claude = raw_claude.reset_index(drop=True)
raw_claude.head()

,job_title,job_location,job_salary,job_summary,is_AI,source
0,Lead ML Engineer,"Minneapolis, MN 55401","$80,000 - $100,000 a year",Cascade Analytics is a rapidly expanding analy...,1,claude ai
1,Senior Data Engineer,"Pittsburgh, PA 15201","$130,000 - $160,000 a year",Apex Intelligence Corp is a fast-growing AI st...,1,claude ai
2,Senior Data Scientist,"Dallas, TX 75251",NaN,Clarity Analytics is a mission-driven analytic...,1,claude ai
3,MLOps Engineer,"Charlotte, NC 28201","$100,000 - $130,000 a year",CoreMetrics Inc. is a global leader in busines...,1,claude ai
4,Data Science Manager,"New York, NY","$150,000 - $190,000 a year",Meridian Data Solutions is a cutting-edge data...,1,claude ai

In [22]:
raw_gemini = pd.read_csv("gemini_data.csv")
raw_gemini['is_AI'] = 1
raw_gemini['source'] = 'gemini ai'
# renaming colums to match the other datasets
raw_gemini = raw_gemini.rename(columns={"jobtitle": "job_title", "joblocation": "job_location", "jobsalary": "job_salary", "jobsummary": "job_summary"})
raw_gemini.head()

,job_title,job_location,job_salary,job_summary,is_AI,source
0,Data Scientist,"New York, NY","$140,000 - $190,000 a year",Quick note: We value curiosity over pedigree h...,1,gemini ai
1,Sr. Data Scientist,"San Francisco, CA","From $150,000",Are you tired of big corporate red tape? We ar...,1,gemini ai
2,Sr. Data Scientist,"Austin, TX",$115k - $160k,"Looking for a builder, not just a researcher. ...",1,gemini ai
3,Staff AI Scientist,"Chicago, IL",$115k - $160k,"Looking for a builder, not just a researcher. ...",1,gemini ai
4,Machine Learning Engineer (Remote),Remote,NaN,We're growing fast and need someone to hit the...,1,gemini ai

In [23]:
raw_chatgpt = pd.read_csv("chatgpt_data.csv")
raw_chatgpt['is_AI'] = 1
raw_chatgpt['source'] = 'chatgpt ai'
raw_chatgpt = raw_chatgpt.rename(columns={"jobtitle": "job_title", "joblocation": "job_location", "jobsalary": "job_salary", "jobsummary": "job_summary"})
raw_chatgpt.head()

,job_title,job_location,job_salary,job_summary,is_AI,source
0,Senior Data Scientist,Remote,NaN,Our client is hiring a Data Scientist to suppo...,1,chatgpt ai
1,Senior Data Scientist,"Boston, MA",NaN,This role sits within a cross-functional analy...,1,chatgpt ai
2,ML Engineer,"Austin, TX","$120,000 - $150,000 a year",Join a fast-moving team working on real-world ...,1,chatgpt ai
3,Data Science Manager,"Boston, MA",NaN,This role sits within a cross-functional analy...,1,chatgpt ai
4,Data Science Manager,"Chicago, IL","$120,000 - $150,000 a year",Join a fast-moving team working on real-world ...,1,chatgpt ai

In [31]:
raw_copilot = pd.read_csv("copilot_data.csv")
raw_copilot['is_AI'] = 1
raw_copilot['source'] = 'copilot ai'
raw_copilot.head()

,job_title,job_location,job_salary,job_summary,is_AI,source
0,Senior Data Scientist,"New York, NY",NaN,"We are a growing, innovation-focused company t...",1,copilot ai
1,"Applied Scientist, ML","Boston, MA",NaN,This company operates at the intersection of a...,1,copilot ai
2,Principal Data Scientist,"New York, NY",NaN,This company operates at the intersection of a...,1,copilot ai
3,Senior Data Scientist,"Atlanta, GA","$120,000 - $160,000 a year","We are a growing, innovation-focused company t...",1,copilot ai
4,"Applied Scientist, ML","Boston, MA","$120,000 - $160,000 a year",Our organization is a well-established technol...,1,copilot ai

In [32]:
raw_preplixity = pd.read_csv("preplixity_data.csv")
raw_preplixity['is_AI'] = 1
raw_preplixity['source'] = 'preplixity ai'
raw_preplixity = raw_preplixity.rename(columns={"jobtitle": "job_title", "joblocation": "job_location", "jobsalary": "job_salary", "jobsummary": "job_summary"})
# dropping extra columns
raw_preplixity = raw_preplixity.drop(columns=["company","jobtype","posted_date"])
raw_preplixity.head()

,job_title,job_location,job_salary,job_summary,is_AI,source
0,ML Research Scientist,"San Francisco, CA 94105",NaN,Role Summary:\nNorthbridge Analytics is seekin...,1,preplixity ai
1,Quantitative Data Scientist,"Boston, MA 02110","$90,851 - $150,580 a year",Role Summary:\nSummit Analytics is seeking a Q...,1,preplixity ai
2,Data Scientist,"Dallas, TX 75201",NaN,Position Overview:\nBrightline AI is looking f...,1,preplixity ai
3,Senior Data Scientist,"Atlanta, GA 30303","$138,520 - $171,803 a year",About the Role:\nSignalPath Data is seeking a ...,1,preplixity ai
4,ML Research Scientist,"Seattle, WA 98101",$101 - $123 an hour,Role Summary:\nNorthbridge Analytics is seekin...,1,preplixity ai

In [37]:
# combining datasets
combined = pd.concat([raw_1500, raw_claude, raw_chatgpt, raw_copilot, raw_gemini, raw_preplixity], ignore_index=True)
# shuffling raw order to mix up the postings
combined = combined.sample(frac=1, random_state=1).reset_index(drop=True)
# saving combined dataset
combined.to_csv("combined.csv", index=False)

In [40]:
combined.head(50)

,job_title,job_location,job_salary,job_summary,is_AI,source
0,Data Science Manager,"Chicago, IL","$120,000 - $150,000 a year",Our client is hiring a Data Scientist to suppo...,1,chatgpt ai
1,AI Engineer,"Boston, MA","$120,000 - $150,000 a year",This role sits within a cross-functional analy...,1,chatgpt ai
2,Statistician - Behavioral Biology,"Silver Spring, MD 20910",NaN,Overview: About The Geneva Foundation ...,0,human
3,Data Science Lead,"Chicago, IL 60601",NaN,Pinnacle AI Labs is a world-class research and...,1,claude ai
4,Data Scientist,"Boston, MA 02124",NaN,The Opportunity MassMutual’s Advanced Analy...,0,human
5,Data Engineer,"Plano, TX",NaN,Overview PepsiCo operates in an environme...,0,human
6,Senior Data Science Analyst,"Phoenix, AZ 85004","$94,000 - $132,000 a year",Permanent opportunity with a FULL suite of b...,0,human
7,Cloud Data Engineer II - Enterprise Analytics ...,"Hartford, CT","$113,900 - $188,000 a year",...,0,human
8,AI Product Manager,"Boston, MA 02119",NaN,Overview: As a national leader in the co...,0,human
9,Data Scientist,"Seattle, WA","$120,000 - $150,000 a year",We’re looking for someone to join our growing ...,1,chatgpt ai
10,"Senior Associate, Data Science - Financial Ser...","Plano, TX",NaN,"Plano 6 (31066), United States of America, P...",0,human
11,Lead Systems Architect - Cyber Data Science,"Irving, TX",NaN,About this role: Wells Fargo is seeking a ...,0,human
12,Quantitative Data Scientist,"Chicago, IL 60601",NaN,Job Summary:\nSkyline Quant is seeking a Quant...,1,preplixity ai
13,Big Data Developer 01,"Portland, ME 04101",NaN,Big Data Developer with Bachelor’s degree i...,0,human
14,"Associate, Polling & Analytics","Washington, DC 20036","$49,000 - $55,000 a year","Launched in 2016, The Hub Project is a non...",0,human
15,Senior Data Scientist,"Worcester, MA 01605",NaN,NovaSpark Technologies is an innovative techno...,1,claude ai
16,Senior Machine Learning Engineer,"Boston, MA","$150,000 - $200,000 a year",About Our Client We are the global leader i...,0,human
17,"Data Scientist, Product Analytics","Atlanta, GA 30303",NaN,Position Overview:\nSkyline Quant is looking f...,1,preplixity ai
18,Data Science Consultant,"San Francisco, CA 94105",NaN,HorizonMind Analytics is a high-growth analyti...,1,claude ai
19,Senior Data Scientist,"Seattle, WA","$120,000 - $150,000 a year",We’re looking for someone to join our growing ...,1,chatgpt ai
20,Analytics Manager,"San Francisco, CA 94105",NaN,Job Summary:\nParallel Orbit is looking for a ...,1,preplixity ai
21,Senior Data Scientist,"Santa Clara, CA 95054","$120,000 - $150,000 a year",Who is Recruiting from Scratch: Recru...,0,human
22,"Assistant Director, Enterprise Insights","Milwaukee, WI","From $130,340 a year","AT NORTHWESTERN MUTUAL, WE ARE STRONG...",0,human
23,Earth Science: Application of Machine Learning...,"Greenbelt, MD",NaN,Organization National Aeronautics ...,0,human
24,Analytics Manager,"Denver, CO 80202","$168,561 - $211,869 a year",Role Summary:\nVertex Insights is seeking a An...,1,preplixity ai
25,Senior Cyber Applied Mathematician,"Dayton, OH",NaN,Battelle delivers when others can’t. We condu...,0,human
26,Data Scientist,"Boston, MA","From $150,000",Quick note: We value curiosity over pedigree h...,1,gemini ai
27,Data Intelligence Analyst,"Atlanta, GA 30301","$100,000 - $130,000 a year",ProNexus Solutions is a results-oriented techn...,1,claude ai
28,Senior Decision Science Analyst - Hybrid,"Oklahoma City, OK",NaN,Position Title: Senior Decision Science ...,0,human
29,Corporate Claims Business Analyst III,Michigan,NaN,"This position is Hybrid Remote in Lansing, MI...",0,human
30,"Lead Software Engineer, Data Engineering","Mc Farland, WI 53558","$85,300 - $170,000 a year",The Role: Data Engineer Location: Team is in...,0,human
31,AI Engineer/Data Scientist,"Minneapolis, MN 55411","$130,000 - $160,000 a year",Benefits/Perks Competitive Compensation Flex...,0,human
32,Data Engineer,"Chicago, IL 60601",NaN,"About JSSI For more than 30 years, Je...",0,human
33,SR. DATA SCIENTIST,"Boston, MA","From $150,000","Looking for a builder, not just a researcher. ...",1,gemini ai
34,Lead Data Scientist,"Boston, MA","$130,000 - $175,000 a year","We are a growing, innovation-focused company t...",1,copilot ai
35,"Data Scientist- TikTok Ads, Ad Inventory & Use...","Mountain View, CA","$153,000 - $296,000 a year",Responsibilities TikTok is the leading destin...,0,human
36,Research Engineer – NLP,"Worcester, MA 01605","$85,000 - $110,000 a year",IntelliCore Systems is a well-established tech...,1,claude ai
37,AI/ML Software Engineer,"Aberdeen Proving Ground, MD 21005",NaN,AI/ML Software Engineer Job Category: Engi...,0,human
38,Senior Data Scientist,Remote,"$150,000 - $210,000 a year",This company operates at the intersection of a...,1,copilot ai
39,Analytics Scientist,"Chicago, IL","$120,000 - $160,000 a year","We are a growing, innovation-focused company t...",1,copilot ai
40,Data Scientist,"New York, NY",NaN,Join a fast-moving team working on real-world ...,1,chatgpt ai
41,"Registered Nurse, Acute","Cincinnati, OH 45206",$30.91 - $38.92 an hour,Description Expected Starting Salary Range:...,0,human
42,All Source / Target Digital Network Analyst,"Annapolis Junction, MD 20701","$130,000 - $160,000 a year",All Source / Target Digital Network Analyst Ep...,0,human
43,Transportation Data Analyst,"Clinton, NY 13323",NaN,SUMMARY: Transportation Data Analyst opportuni...,0,human
44,Data Engineer - MacDill AFB- Tampa FL,"Macdill AFB, FL 33621","$112,000 - $179,000 a year",Responsibilities: In support of the Op...,0,human
45,Data Analyst,"Lafayette, LA 70506",NaN,"Job Details Job Location: Lafayette, LA - L...",0,human
46,Senior Data Scientist,"Austin, TX",NaN,Join a fast-moving team working on real-world ...,1,chatgpt ai
47,Analytics Lead,Remote,NaN,We’re looking for someone to join our growing ...,1,chatgpt ai
48,Database Architect,"Washington, DC","$160,000 - $200,000 a year",Pinnacle AI Labs is a world-class research and...,1,claude ai
49,Data and Statistical Analyst – health and huma...,"St. Louis, MO 63101",NaN,Liberty Healthcare helps ensure people with i...,0,human

In [27]:
# number of entries in combined:
len(combined)

3000

In [7]:
# NLTK to remove stopwords?